SELECT TOP (1000) [id]
      ,[nombre]
      ,[tipoDeInstitución]
      ,[nivel]
      ,[modalidad]
      ,[director]
      ,[fechaDeFundacion]
      ,[turno]
      ,[aniosACursar]
      ,[capacidadDeAlumnos]
      ,[provincia]
      ,[localidad]
      ,[direccion]
      ,[cantDeCompPorEntregar]
      ,[computadorasEntregadas]
      ,[anioAlCualFueEntrgado]
      ,[computadorasRestantes]
      ,[inconvenientes]
  FROM [ProyectoHuayra].[dbo].[escuelasregistradas]